# Generated by Django 5.1.3 on 2025-01-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_Lot', models.CharField(max_length=255)),
                ('Document_Number', models.CharField(max_length=255)),
                ('Item_Number', models.CharField(max_length=255)),
                ('Cross_Reference', models.CharField(max_length=255)),
                ('QTY', models.CharField(max_length=255)),
                ('Box', models.CharField(max_length=255)),
                ('Invoice', models.CharField(max_length=255)),
                ('Invoice_Date', models.CharField(max_length=255)),
                ('Packing_List', models.CharField(max_length=255)),
                ('Qarbon_Qty', models.CharField(max_length=255)),
                ('Lot_Carbon', models.CharField(max_length=255)),
                ('Pallet', models.CharField(max_length=255)),
            ],
        ),
    ]
