# Generated by Django 5.1.3 on 2025-01-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='Box',
            new_name='box',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='Cross_Reference',
            new_name='cross_reference',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='Document_Number',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='Invoice',
            new_name='document_number',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='Invoice_Date',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='Item_Number',
            new_name='invoice_date',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='Lot_Carbon',
            new_name='item_number',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='Packing_List',
            new_name='lot_carbon',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='Pallet',
            new_name='packing_list',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='QTY',
            new_name='pallet',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='Qarbon_Qty',
            new_name='qarbon_qty',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='Serial_Lot',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='shipment',
            name='serial_lot',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
