# Generated by Django 5.1.3 on 2025-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_rename_box_shipment_box_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.CharField(max_length=255, unique=True)),
                ('length_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('width_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
