# Generated by Django 5.1.3 on 2025-01-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_palletdimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palletdimension',
            name='pallet',
        ),
        migrations.AddField(
            model_name='palletdimension',
            name='pallet_number',
            field=models.CharField(default='Unknown', max_length=10, unique=True),
        ),
    ]
