# Generated by Django 5.1.3 on 2025-01-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_remove_palletdimension_pallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palletdimension',
            name='pallet_number',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
