# Generated by Django 5.1.3 on 2025-01-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_palletdimension_pallet_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='palletdimension',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
