# Generated by Django 5.1.3 on 2024-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('random_id', models.IntegerField()),
                ('selected_option', models.CharField(max_length=255)),
            ],
        ),
    ]
