# Generated by Django 5.1.3 on 2024-11-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_area', models.EmailField(max_length=254)),
                ('text_area', models.TextField()),
            ],
        ),
    ]
